apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command: ['cat']
    tty: true
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: "256Mi"
        cpu: "200m"
